# Generated by Django 4.2.27 on 2025-12-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_process', models.CharField(max_length=100, verbose_name='نام فعالیت')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد فعالیت')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='به روزرسانی فرایند')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.member', verbose_name='ایجاد کننده فعالیت')),
            ],
            options={
                'verbose_name_plural': 'توضیحات فرایندها',
                'db_table': 'Detail_Process',
            },
        ),
        migrations.CreateModel(
            name='Execute_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_work', models.CharField(max_length=100, verbose_name='نام عمل اقدام شده')),
                ('description_work', models.TextField(verbose_name='متن توضیحات')),
                ('document1_work', models.FileField(blank=True, null=True, upload_to='', verbose_name='سند3 ایجاد شده در این بخش اجرایی')),
                ('document2_work', models.FileField(blank=True, null=True, upload_to='', verbose_name='سند2 ایجاد شده در این بخش اجرایی')),
                ('document3_work', models.FileField(blank=True, null=True, upload_to='', verbose_name='سند3 ایجاد شده در این بخش اجرایی')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد اقدام')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='به روزرسانی  زمان اقدام')),
                ('result_work', models.TextField(verbose_name='نتیجه این عمل صورت گرفته')),
                ('process_of_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.detail_process', verbose_name='فرایند مرجع')),
                ('worker_of_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.member', verbose_name='ایجاد کننده فعالیت')),
            ],
            options={
                'verbose_name_plural': 'ریز اقدامات فرایند ها',
                'db_table': 'Execute_Process',
            },
        ),
    ]
