# Generated by Django 4.2.27 on 2025-12-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_process',
            name='name_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.detail_project', verbose_name='پروژه مرجع'),
        ),
    ]
