# Generated by Django 4.2.27 on 2025-12-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('process', '0002_detail_process_name_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execute_process',
            name='worker_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.member', verbose_name='انجام دهنده فعالیت در این فرایند '),
        ),
    ]
