# Generated by Django 4.2.27 on 2025-12-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100, verbose_name='نام پروژه')),
            ],
            options={
                'verbose_name_plural': 'پروژه ها',
                'db_table': 'Detail_Project',
            },
        ),
    ]
