# Generated by Django 4.2.27 on 2025-12-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_member', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'اعضای تیم',
                'db_table': 'Member',
            },
        ),
    ]
